#
# This source file is part of the Apodini Template open source project
#
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

FROM swiftlang/swift:nightly-5.5-focal
RUN apt-get update && apt-get install -y --no-install-recommends libsqlite3-dev