name: Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  macoswebservices:
    name: macOS
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest
    - name: Check Xcode version
      run: xcodebuild -version
    - name: Check Swift version
      run: swift --version
    - name: Build and test
      run: swift test
  linuxwebservices:
    name: Linux ${{ matrix.linux }}
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.linux }}
    strategy:
      matrix:
        linux: [focal, bionic, amazonlinux2, centos8]
    steps:
    - uses: actions/checkout@v2
    - name: Install libsqlite3
      if: ${{ !(startsWith( matrix.linux, 'centos' ) || startsWith( matrix.linux, 'amazonlinux' )) }}
      run: apt-get update && apt-get install -y --no-install-recommends libsqlite3-dev
    - name: Install libsqlite3
      if: startsWith( matrix.linux, 'amazonlinux' )
      run: yum update -y && yum install -y sqlite-devel
    - name: Install libsqlite3
      if: startsWith( matrix.linux, 'centos' )
      run: yum update -y --nobest && yum install -y sqlite-devel
    - name: Check Swift version
      run: swift --version
    - name: Build and test
      run: swift test -Xswiftc -Xfrontend -Xswiftc -sil-verify-none
