#                   
# This source file is part of the Apodini Template open source project
# 
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
# 
# SPDX-License-Identifier: MIT
# 

name: Build Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker:
    name: Docker Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get latest tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        id: buildandpush
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/apodini/template:latest,ghcr.io/apodini/template:${{ steps.latesttag.outputs.tag }}
      - name: Image digest
        run: echo ${{ steps.buildandpush.outputs.digest }}
